//------------------------------------------------------------------------
// Copyright(c) 2022 natas.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"NetProcess.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"NetProcess VST3 (64Bit)"
#else
#define stringFileDescription	"NetProcess VST3"
#endif
#define stringCompanyName		"natas\0"
#define stringLegalCopyright	"Copyright(c) 2022 natas."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
